[package]
name = "gofi"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
alloy="*"
hex="*"
sha3="*"
redis="0.32"
postgres="*"
once_cell="*"
serde={version="*", features = ["derive"]}
serde_json="*"
serde_yaml="*"
secp256k1="*"
